api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/web-servers"
  id = "paketo-buildpacks/web-servers"
  name = "Paketo Buildpack for Web Servers"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/web-servers/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.5"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.5"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.11.1"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "2.2.9"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "2.6.9"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.9"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "1.0.3"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "0.2.68"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.5"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.5"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.11.1"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "2.2.3"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.9"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "1.0.3"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "0.2.68"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.5"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.5"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.11.1"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "2.2.9"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "2.6.9"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.9"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.7.72"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "0.2.68"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.5"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.5"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.11.1"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "2.2.3"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.9"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.7.72"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "0.2.68"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.5"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.5"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "1.0.3"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "0.2.68"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.5"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.5"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.7.72"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.4"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.3"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "0.2.68"
