api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/web-servers"
  id = "paketo-buildpacks/web-servers"
  name = "Paketo Buildpack for Web Servers"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/web-servers/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "README.md", "buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.13.2"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "2.2.16"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "2.6.16"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.17"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "1.0.9"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.8"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.13.2"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "2.2.8"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.17"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "1.0.9"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.8"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.13.2"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "2.2.16"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "2.6.16"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.17"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "1.0.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.8"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.13.2"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "2.2.8"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.17"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "1.0.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.8"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.0"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "1.0.9"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.8"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.0"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "1.0.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.8"
