api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/web-servers"
  id = "paketo-buildpacks/web-servers"
  name = "Paketo Buildpack for Web Servers"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/web-servers/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "README.md", "buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.0.3"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "2.2.22"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "2.7.1"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.23"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "1.0.14"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.14"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.0.3"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "2.3.6"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.23"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "1.0.14"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.14"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.0.3"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "2.2.22"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "2.7.1"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.23"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "1.0.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.14"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.0.3"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "2.3.6"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    version = "2.3.23"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "1.0.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.14"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "1.0.14"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.14"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "1.0.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

  [[order.group]]
    id = "paketo-buildpacks/source-removal"
    version = "1.0.14"
